{
    "Attributes": {
        "Error": "Traceback (most recent call last):\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 682, in processing\n    executable,arguments = prepare_recipe(args,tempdir)\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 737, in prepare_recipe\n    executable=get_recipe_executable(recipe[0],d_t=tempdir)\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 351, in get_recipe_executable\n    raise RuntimeError('Cannot find recipe: {}'.format(d_s))\nRuntimeError: Cannot find recipe: /Users/josefk/github/private/seppo/recipies/sentinel/seppo_sentinel_update_allPaths.sh\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 788, in <module>\n    main()\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 784, in main\n    return processing(args)\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 690, in processing\n    raise RuntimeError(\"Error preparing recipe or input data {}\\n{}\".format(args.recipe,args.input))\nRuntimeError: Error preparing recipe or input data /Users/josefk/github/private/seppo/recipies/sentinel/seppo_sentinel_update_allPaths.sh -H ebddbinstance.cbstdhjsojep.us-east-1.rds.amazonaws.com\nNone\n"
    },
    "Duration_hms": "0:00:05.009647",
    "Duration_sec": "5.009647",
    "EndTime": "2019-03-05T22:11:07.081327",
    "Job": "seppo_recipe_processor.py -r '/Users/josefk/github/private/seppo/recipies/sentinel/seppo_sentinel_update_allPaths.sh -H ebddbinstance.cbstdhjsojep.us-east-1.rds.amazonaws.com'",
    "JobID": "sentinelinventory",
    "StartTime": "2019-03-05T22:11:02.071680",
    "User": "josefk"
}
-----------------------------------------------------------
{
    "Attributes": {
        "Error": "Traceback (most recent call last):\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 682, in processing\n    executable,arguments = prepare_recipe(args,tempdir)\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 737, in prepare_recipe\n    executable=get_recipe_executable(recipe[0],d_t=tempdir)\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 351, in get_recipe_executable\n    raise RuntimeError('Cannot find recipe: {}'.format(d_s))\nRuntimeError: Cannot find recipe: /Users/josefk/github/private/seppo/recipies/sentinel/seppo_sentinel_update_allPaths.sh\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 788, in <module>\n    main()\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 784, in main\n    return processing(args)\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 690, in processing\n    raise RuntimeError(\"Error preparing recipe or input data {}\\n{}\".format(args.recipe,args.input))\nRuntimeError: Error preparing recipe or input data /Users/josefk/github/private/seppo/recipies/sentinel/seppo_sentinel_update_allPaths.sh -H ebddbinstance.cbstdhjsojep.us-east-1.rds.amazonaws.com\nNone\n"
    },
    "Duration_hms": "0:00:05.042795",
    "Duration_sec": "5.042795",
    "EndTime": "2019-03-05T22:11:21.397126",
    "Job": "seppo_recipe_processor.py -r '/Users/josefk/github/private/seppo/recipies/sentinel/seppo_sentinel_update_allPaths.sh -H ebddbinstance.cbstdhjsojep.us-east-1.rds.amazonaws.com'",
    "JobID": "sentinelinventory",
    "StartTime": "2019-03-05T22:11:16.354331",
    "User": "josefk"
}
-----------------------------------------------------------
{
    "Attributes": {
        "Error": "Traceback (most recent call last):\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 682, in processing\n    executable,arguments = prepare_recipe(args,tempdir)\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 737, in prepare_recipe\n    executable=get_recipe_executable(recipe[0],d_t=tempdir)\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 351, in get_recipe_executable\n    raise RuntimeError('Cannot find recipe: {}'.format(d_s))\nRuntimeError: Cannot find recipe: /Users/josefk/github/private/seppo/recipies/sentinel/seppo_sentinel_update_allPaths.sh\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 788, in <module>\n    main()\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 784, in main\n    return processing(args)\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 690, in processing\n    raise RuntimeError(\"Error preparing recipe or input data {}\\n{}\".format(args.recipe,args.input))\nRuntimeError: Error preparing recipe or input data /Users/josefk/github/private/seppo/recipies/sentinel/seppo_sentinel_update_allPaths.sh -H ebddbinstance.cbstdhjsojep.us-east-1.rds.amazonaws.com\nNone\n"
    },
    "Duration_hms": "0:00:05.010672",
    "Duration_sec": "5.010672",
    "EndTime": "2019-03-05T22:11:35.633533",
    "Job": "seppo_recipe_processor.py -r '/Users/josefk/github/private/seppo/recipies/sentinel/seppo_sentinel_update_allPaths.sh -H ebddbinstance.cbstdhjsojep.us-east-1.rds.amazonaws.com'",
    "JobID": "sentinelinventory",
    "StartTime": "2019-03-05T22:11:30.622861",
    "User": "josefk"
}
-----------------------------------------------------------
{
    "Attributes": {
        "Error": "Traceback (most recent call last):\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 682, in processing\n    executable,arguments = prepare_recipe(args,tempdir)\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 737, in prepare_recipe\n    executable=get_recipe_executable(recipe[0],d_t=tempdir)\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 351, in get_recipe_executable\n    raise RuntimeError('Cannot find recipe: {}'.format(d_s))\nRuntimeError: Cannot find recipe: /Users/josefk/github/private/seppo/recipies/sentinel/seppo_sentinel_update_allPaths.sh\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 788, in <module>\n    main()\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 784, in main\n    return processing(args)\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 690, in processing\n    raise RuntimeError(\"Error preparing recipe or input data {}\\n{}\".format(args.recipe,args.input))\nRuntimeError: Error preparing recipe or input data /Users/josefk/github/private/seppo/recipies/sentinel/seppo_sentinel_update_allPaths.sh -H ebddbinstance.cbstdhjsojep.us-east-1.rds.amazonaws.com\nNone\n"
    },
    "Duration_hms": "0:00:05.009760",
    "Duration_sec": "5.00976",
    "EndTime": "2019-03-05T22:11:50.126710",
    "Job": "seppo_recipe_processor.py -r '/Users/josefk/github/private/seppo/recipies/sentinel/seppo_sentinel_update_allPaths.sh -H ebddbinstance.cbstdhjsojep.us-east-1.rds.amazonaws.com'",
    "JobID": "sentinelinventory",
    "StartTime": "2019-03-05T22:11:45.116950",
    "User": "josefk"
}
-----------------------------------------------------------
{
    "Attributes": {
        "Error": "Traceback (most recent call last):\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 682, in processing\n    executable,arguments = prepare_recipe(args,tempdir)\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 737, in prepare_recipe\n    executable=get_recipe_executable(recipe[0],d_t=tempdir)\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 351, in get_recipe_executable\n    raise RuntimeError('Cannot find recipe: {}'.format(d_s))\nRuntimeError: Cannot find recipe: /Users/josefk/github/private/seppo/recipies/sentinel/seppo_sentinel_update_allPaths.sh\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 788, in <module>\n    main()\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 784, in main\n    return processing(args)\n  File \"/s/seppo/commands/seppo_recipe_processor.py\", line 690, in processing\n    raise RuntimeError(\"Error preparing recipe or input data {}\\n{}\".format(args.recipe,args.input))\nRuntimeError: Error preparing recipe or input data /Users/josefk/github/private/seppo/recipies/sentinel/seppo_sentinel_update_allPaths.sh -H ebddbinstance.cbstdhjsojep.us-east-1.rds.amazonaws.com\nNone\n"
    },
    "Duration_hms": "0:00:05.009302",
    "Duration_sec": "5.009302",
    "EndTime": "2019-03-05T22:12:04.347361",
    "Job": "seppo_recipe_processor.py -r '/Users/josefk/github/private/seppo/recipies/sentinel/seppo_sentinel_update_allPaths.sh -H ebddbinstance.cbstdhjsojep.us-east-1.rds.amazonaws.com'",
    "JobID": "sentinelinventory",
    "StartTime": "2019-03-05T22:11:59.338059",
    "User": "josefk"
}
-----------------------------------------------------------
seppo_recipe_processor.py -r '/Users/josefk/github/private/seppo/recipies/sentinel/seppo_sentinel_update_allPaths.sh -H ebddbinstance.cbstdhjsojep.us-east-1.rds.amazonaws.com'
-----------------------------------------------------------
